## Introduction to Numpy:

- Thing of all data fundamentally as arrays of numbers;
- No matter what the data are, the first step in making it analyzable will be to transform them into array of numbers.

### Understanding Data Types in Python
- Differences between how python handles array of data by itself and how NumPy improves on this.

In [4]:
result = 0
for i in range(100):
    result += i 
i

99

In [5]:
import numpy as np
np.__version__


'1.24.1'

- A python list is more than just a List

In [7]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
type(L[0])

int

In [11]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [12]:
type(L2[0])

str

## Fixed-Type Arrays

- How To Create NumPy Arrays

In [15]:
# integer array:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

- NumPy is constrained to arrays that all contain the same type.

In [17]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

- Unlike python lists, NumPy arrays can be explicitly be multi-dimensional.

In [19]:
# nested lists results in multi-dimensional array
np.array([range(i,i+3) for i in (2, 4, 6)])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch
- Especially for large arrays, it is more efficient to create arrays from scratch using routines built into NumPy. 

In [22]:
# Create a 10 length integer array  filled with zeros
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
# Create a 3x5 floating-point array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [28]:
# Create an array filled with a linear sequence
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1

np.random.random((3,3))

array([[0.08250233, 0.9182452 , 0.41765994],
       [0.16372936, 0.58046665, 0.39721869],
       [0.37140485, 0.3616822 , 0.43340742]])

In [36]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1, (3,3))

array([[-0.16006747, -1.71978906,  0.46708359],
       [ 0.64770712, -1.03685835, -1.86860124],
       [-0.17627524, -1.17287116, -0.13040701]])

In [38]:
# Create a 3x3 array of random integers in the interval 0 to 10
np.random.randint(0, 10, (3,3))

array([[6, 1, 1],
       [5, 3, 1],
       [6, 8, 4]])

In [40]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])