## Numpy Basics
- Attributes of Arrays: Determining the size, shape, memory consumption etc;
- Indexing of Arrays;
- Slicing of Arrays;
- Reshaping of Arrays;
- Joining and Splitting of Arrays.

In [12]:
import numpy as np
np.random.seed(0)


x1 = np.random.randint(10, size= 6) 
x2 = np.random.randint(10, size= (3, 4))
x3 = np.random.randint(10, size=(3,4,5))

- Each array has attributes ndim(number of dimensions), shape (size of each dimension) and size (total size of the array). Another useful attribute is dtype.

In [17]:
print("x3 ndim = ",x3.ndim)
print("x3 shape = ",x3.shape)
print("x3 size = ",x3.size)
print("x3 dtype =", x3.dtype)

x3 ndim =  3
x3 shape =  (3, 4, 5)
x3 size =  60
x3 dtype = int32


## Array Indexing: Accessing Single Elements
Similar to python list indexing.

In [23]:
print(x1)
print(x1[0])
print(x1[4])

[5 0 3 3 7 9]
5
7


- To index from the end of array, you can use negative indices

In [28]:
print(x1)
print(x1[-1])
print(x1[-2])

[5 0 3 3 7 9]
9
7


- In multi-dimensional arrays, items can be accessed using a comma-separated tuple of indices.

In [36]:
print(x2)
print()
print(x2[1,0])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

7


- The values can be modified using index notation:

In [39]:
x2[0,0] = 12
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Array Slicing: Accessing SubArrays
- We can access subarrays in python using the slicing notation '(:)', in one-dimension or multi-dimension arrays:
- x[start:stop:step]

In [42]:
# One-dimensional Array
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
x[:5] # First 5 elements

array([0, 1, 2, 3, 4])

In [46]:
x[5:] # Elements after index 5

array([5, 6, 7, 8, 9])

In [49]:
x[4:7] # middle subarray

array([4, 5, 6])

In [52]:
x[::2] # Every other element

array([0, 2, 4, 6, 8])

In [54]:
x[1::2] # Every other element starting at Index 1

array([1, 3, 5, 7, 9])

- When Step Value is Negative, the defaults for start and stop are swapped.

In [56]:
x[::-1] # all the elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [58]:
x[5::-2] # reversed every other from the index 5

array([5, 3, 1])

In [60]:
# Multi Dimensional Arrays
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [62]:
x2[:2, :3] # two rows, three columns 

array([[12,  5,  2],
       [ 7,  6,  8]])

In [65]:
x2[:3, ::2] # 3 rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [67]:
# Reversed multi dimensional array
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

- It's possible to access a single row or column of an array, combining indexing and slicing notation:

In [72]:
print(x2[:,0]) # first column of x2

[12  7  1]


In [75]:
print(x2[0,:]) # first row of x2

[12  5  2  4]


### SubArrays as no-copy views
- In python lists, the array slices will be copies. In NumPy array, the slices will be VIEWS.

In [77]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [80]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [83]:
x2_sub[0,0] = 99
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Creating copies of Arrays
- We can create a copy of original array or subarray, and modify it without modify the original array.

In [86]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [88]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [90]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays
- We can use the 'reshape' method to reshaping arrays.

In [95]:
# 1 through 9 in a 3x3 grid.
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.

In [104]:
x = np.array([1,2,3])
x.reshape((1,3))


array([[1, 2, 3]])

In [109]:
# row vector via newaxis
x[np.newaxis,:]

array([[1, 2, 3]])

In [110]:
# column vector via reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [113]:
# Column Vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting
- Combine Multiple arrays into one, and to conversely split a single array into multiple arrays.

### Concatenation of Arrays
- Concatenation or joining arrays in NumPy is primarily accomplished using the routines 'np.concatenate', 'np.vstack' and 'np.hstack'. 

In [118]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])


array([1, 2, 3, 4, 5, 6])

In [120]:
# It can also be used for two-dimensional arrays:
grid = np.array([[1,2,3],
                [4,5,6]])

In [122]:
np.concatenate([grid,grid]) # concatenate along the first axis

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [124]:
# concatenate along the second axis
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack), and np.hstack (horizontal stack) functions.

In [129]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                [6,5,4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [135]:
# horizontally stack the arrays
y = np.array([[99],
             [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of Arrays
- The opposite of concatenation is splitting, which is implemented using the functions 'np.split', 'np.hsplit' and 'np.vsplit'

In [138]:
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x,(3,5))
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [141]:
grid  = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [149]:
upper, lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [152]:
left, right = np.hsplit(grid, 2)
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
